/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuProductSlugRouteImport } from './routes/menu.$productSlug'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedAccountAddressesRouteImport } from './routes/_authenticated/account.addresses'
import { Route as AuthenticatedAccountChallengesRouteImport } from './routes/_authenticated/account.challenges'
import { Route as AuthenticatedAccountFavoritesRouteImport } from './routes/_authenticated/account.favorites'
import { Route as AuthenticatedAccountInboxRouteImport } from './routes/_authenticated/account.inbox'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated/account.notifications'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedAccountRewardsRouteImport } from './routes/_authenticated/account.rewards'
import { Route as AuthenticatedAccountVouchersRouteImport } from './routes/_authenticated/account.vouchers'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner.index'
import { Route as AuthenticatedOwnerAccountRouteImport } from './routes/_authenticated/owner.account'
import { Route as AuthenticatedOwnerBannersRouteImport } from './routes/_authenticated/owner.banners'
import { Route as AuthenticatedOwnerChallengesRouteImport } from './routes/_authenticated/owner.challenges'
import { Route as AuthenticatedOwnerCombosRouteImport } from './routes/_authenticated/owner.combos'
import { Route as AuthenticatedOwnerCouponsRouteImport } from './routes/_authenticated/owner.coupons'
import { Route as AuthenticatedOwnerCustomersRouteImport } from './routes/_authenticated/owner.customers'
import { Route as AuthenticatedOwnerDeliveryRouteImport } from './routes/_authenticated/owner.delivery'
import { Route as AuthenticatedOwnerFinanceRouteImport } from './routes/_authenticated/owner.finance'
import { Route as AuthenticatedOwnerInboxRouteImport } from './routes/_authenticated/owner.inbox'
import { Route as AuthenticatedOwnerInventoryRouteImport } from './routes/_authenticated/owner.inventory'
import { Route as AuthenticatedOwnerMenuRouteImport } from './routes/_authenticated/owner.menu'
import { Route as AuthenticatedOwnerMyAccountRouteImport } from './routes/_authenticated/owner.my-account'
import { Route as AuthenticatedOwnerOrdersRouteImport } from './routes/_authenticated/owner.orders'
import { Route as AuthenticatedOwnerPlatformSaleRouteImport } from './routes/_authenticated/owner.platform-sale'
import { Route as AuthenticatedOwnerPlatformsRouteImport } from './routes/_authenticated/owner.platforms'
import { Route as AuthenticatedOwnerPosRouteImport } from './routes/_authenticated/owner.pos'
import { Route as AuthenticatedOwnerPurchasesRouteImport } from './routes/_authenticated/owner.purchases'
import { Route as AuthenticatedOwnerReportsRouteImport } from './routes/_authenticated/owner.reports'
import { Route as AuthenticatedOwnerReviewsRouteImport } from './routes/_authenticated/owner.reviews'
import { Route as AuthenticatedOwnerRewardsRouteImport } from './routes/_authenticated/owner.rewards'
import { Route as AuthenticatedOwnerRidersRouteImport } from './routes/_authenticated/owner.riders'
import { Route as AuthenticatedOwnerSettingsRouteImport } from './routes/_authenticated/owner.settings'
import { Route as AuthenticatedOwnerStaffRouteImport } from './routes/_authenticated/owner.staff'
import { Route as AuthenticatedOwnerStaffAccountsRouteImport } from './routes/_authenticated/owner.staff-accounts'
import { Route as AuthenticatedOwnerSuppliersRouteImport } from './routes/_authenticated/owner.suppliers'
import { Route as AuthenticatedAccountReviewOrderIdRouteImport } from './routes/_authenticated/account.review.$orderId'
import { Route as AuthenticatedOwnerCustomersCustomerIdRouteImport } from './routes/_authenticated/owner.customers.$customerId'
import { Route as AuthenticatedOwnerOrdersIndexRouteImport } from './routes/_authenticated/owner.orders.index'
import { Route as AuthenticatedOwnerOrdersOrderIdRouteImport } from './routes/_authenticated/owner.orders.$orderId'
import { Route as ApiPublicAuthSmsHookRouteImport } from './routes/api/public/auth/sms-hook'
import { Route as ApiPublicCleanupRunRouteImport } from './routes/api/public/cleanup/run'
import { Route as ApiPublicNotificationsDispatchRouteImport } from './routes/api/public/notifications/dispatch'
import { Route as ApiPublicCommunicationWebhookProviderRouteImport } from './routes/api/public/communication/webhook.$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuProductSlugRoute = MenuProductSlugRouteImport.update({
  id: '/menu/$productSlug',
  path: '/menu/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountAddressesRoute =
  AuthenticatedAccountAddressesRouteImport.update({
    id: '/account/addresses',
    path: '/account/addresses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountChallengesRoute =
  AuthenticatedAccountChallengesRouteImport.update({
    id: '/account/challenges',
    path: '/account/challenges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountFavoritesRoute =
  AuthenticatedAccountFavoritesRouteImport.update({
    id: '/account/favorites',
    path: '/account/favorites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountInboxRoute =
  AuthenticatedAccountInboxRouteImport.update({
    id: '/account/inbox',
    path: '/account/inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/account/orders',
    path: '/account/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountRewardsRoute =
  AuthenticatedAccountRewardsRouteImport.update({
    id: '/account/rewards',
    path: '/account/rewards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountVouchersRoute =
  AuthenticatedAccountVouchersRouteImport.update({
    id: '/account/vouchers',
    path: '/account/vouchers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerAccountRoute =
  AuthenticatedOwnerAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerBannersRoute =
  AuthenticatedOwnerBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerChallengesRoute =
  AuthenticatedOwnerChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerCombosRoute =
  AuthenticatedOwnerCombosRouteImport.update({
    id: '/combos',
    path: '/combos',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerCouponsRoute =
  AuthenticatedOwnerCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerCustomersRoute =
  AuthenticatedOwnerCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerDeliveryRoute =
  AuthenticatedOwnerDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerFinanceRoute =
  AuthenticatedOwnerFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerInboxRoute = AuthenticatedOwnerInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerInventoryRoute =
  AuthenticatedOwnerInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerMenuRoute = AuthenticatedOwnerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerMyAccountRoute =
  AuthenticatedOwnerMyAccountRouteImport.update({
    id: '/my-account',
    path: '/my-account',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerOrdersRoute =
  AuthenticatedOwnerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerPlatformSaleRoute =
  AuthenticatedOwnerPlatformSaleRouteImport.update({
    id: '/platform-sale',
    path: '/platform-sale',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerPlatformsRoute =
  AuthenticatedOwnerPlatformsRouteImport.update({
    id: '/platforms',
    path: '/platforms',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerPosRoute = AuthenticatedOwnerPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerPurchasesRoute =
  AuthenticatedOwnerPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerReportsRoute =
  AuthenticatedOwnerReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerReviewsRoute =
  AuthenticatedOwnerReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerRewardsRoute =
  AuthenticatedOwnerRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerRidersRoute =
  AuthenticatedOwnerRidersRouteImport.update({
    id: '/riders',
    path: '/riders',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerSettingsRoute =
  AuthenticatedOwnerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerStaffRoute = AuthenticatedOwnerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerStaffAccountsRoute =
  AuthenticatedOwnerStaffAccountsRouteImport.update({
    id: '/staff-accounts',
    path: '/staff-accounts',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerSuppliersRoute =
  AuthenticatedOwnerSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedAccountReviewOrderIdRoute =
  AuthenticatedAccountReviewOrderIdRouteImport.update({
    id: '/account/review/$orderId',
    path: '/account/review/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerCustomersCustomerIdRoute =
  AuthenticatedOwnerCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedOwnerCustomersRoute,
  } as any)
const AuthenticatedOwnerOrdersIndexRoute =
  AuthenticatedOwnerOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOwnerOrdersRoute,
  } as any)
const AuthenticatedOwnerOrdersOrderIdRoute =
  AuthenticatedOwnerOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOwnerOrdersRoute,
  } as any)
const ApiPublicAuthSmsHookRoute = ApiPublicAuthSmsHookRouteImport.update({
  id: '/api/public/auth/sms-hook',
  path: '/api/public/auth/sms-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCleanupRunRoute = ApiPublicCleanupRunRouteImport.update({
  id: '/api/public/cleanup/run',
  path: '/api/public/cleanup/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsDispatchRoute =
  ApiPublicNotificationsDispatchRouteImport.update({
    id: '/api/public/notifications/dispatch',
    path: '/api/public/notifications/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCommunicationWebhookProviderRoute =
  ApiPublicCommunicationWebhookProviderRouteImport.update({
    id: '/api/public/communication/webhook/$provider',
    path: '/api/public/communication/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/offers': typeof OffersRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/menu/$productSlug': typeof MenuProductSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/menu/': typeof MenuIndexRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/challenges': typeof AuthenticatedAccountChallengesRoute
  '/account/favorites': typeof AuthenticatedAccountFavoritesRoute
  '/account/inbox': typeof AuthenticatedAccountInboxRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/rewards': typeof AuthenticatedAccountRewardsRoute
  '/account/vouchers': typeof AuthenticatedAccountVouchersRoute
  '/owner/account': typeof AuthenticatedOwnerAccountRoute
  '/owner/banners': typeof AuthenticatedOwnerBannersRoute
  '/owner/challenges': typeof AuthenticatedOwnerChallengesRoute
  '/owner/combos': typeof AuthenticatedOwnerCombosRoute
  '/owner/coupons': typeof AuthenticatedOwnerCouponsRoute
  '/owner/customers': typeof AuthenticatedOwnerCustomersRouteWithChildren
  '/owner/delivery': typeof AuthenticatedOwnerDeliveryRoute
  '/owner/finance': typeof AuthenticatedOwnerFinanceRoute
  '/owner/inbox': typeof AuthenticatedOwnerInboxRoute
  '/owner/inventory': typeof AuthenticatedOwnerInventoryRoute
  '/owner/menu': typeof AuthenticatedOwnerMenuRoute
  '/owner/my-account': typeof AuthenticatedOwnerMyAccountRoute
  '/owner/orders': typeof AuthenticatedOwnerOrdersRouteWithChildren
  '/owner/platform-sale': typeof AuthenticatedOwnerPlatformSaleRoute
  '/owner/platforms': typeof AuthenticatedOwnerPlatformsRoute
  '/owner/pos': typeof AuthenticatedOwnerPosRoute
  '/owner/purchases': typeof AuthenticatedOwnerPurchasesRoute
  '/owner/reports': typeof AuthenticatedOwnerReportsRoute
  '/owner/reviews': typeof AuthenticatedOwnerReviewsRoute
  '/owner/rewards': typeof AuthenticatedOwnerRewardsRoute
  '/owner/riders': typeof AuthenticatedOwnerRidersRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/staff': typeof AuthenticatedOwnerStaffRoute
  '/owner/staff-accounts': typeof AuthenticatedOwnerStaffAccountsRoute
  '/owner/suppliers': typeof AuthenticatedOwnerSuppliersRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/account/review/$orderId': typeof AuthenticatedAccountReviewOrderIdRoute
  '/owner/customers/$customerId': typeof AuthenticatedOwnerCustomersCustomerIdRoute
  '/owner/orders/$orderId': typeof AuthenticatedOwnerOrdersOrderIdRoute
  '/api/public/auth/sms-hook': typeof ApiPublicAuthSmsHookRoute
  '/api/public/cleanup/run': typeof ApiPublicCleanupRunRoute
  '/api/public/notifications/dispatch': typeof ApiPublicNotificationsDispatchRoute
  '/owner/orders/': typeof AuthenticatedOwnerOrdersIndexRoute
  '/api/public/communication/webhook/$provider': typeof ApiPublicCommunicationWebhookProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/offers': typeof OffersRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/menu/$productSlug': typeof MenuProductSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/menu': typeof MenuIndexRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/challenges': typeof AuthenticatedAccountChallengesRoute
  '/account/favorites': typeof AuthenticatedAccountFavoritesRoute
  '/account/inbox': typeof AuthenticatedAccountInboxRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/rewards': typeof AuthenticatedAccountRewardsRoute
  '/account/vouchers': typeof AuthenticatedAccountVouchersRoute
  '/owner/account': typeof AuthenticatedOwnerAccountRoute
  '/owner/banners': typeof AuthenticatedOwnerBannersRoute
  '/owner/challenges': typeof AuthenticatedOwnerChallengesRoute
  '/owner/combos': typeof AuthenticatedOwnerCombosRoute
  '/owner/coupons': typeof AuthenticatedOwnerCouponsRoute
  '/owner/customers': typeof AuthenticatedOwnerCustomersRouteWithChildren
  '/owner/delivery': typeof AuthenticatedOwnerDeliveryRoute
  '/owner/finance': typeof AuthenticatedOwnerFinanceRoute
  '/owner/inbox': typeof AuthenticatedOwnerInboxRoute
  '/owner/inventory': typeof AuthenticatedOwnerInventoryRoute
  '/owner/menu': typeof AuthenticatedOwnerMenuRoute
  '/owner/my-account': typeof AuthenticatedOwnerMyAccountRoute
  '/owner/platform-sale': typeof AuthenticatedOwnerPlatformSaleRoute
  '/owner/platforms': typeof AuthenticatedOwnerPlatformsRoute
  '/owner/pos': typeof AuthenticatedOwnerPosRoute
  '/owner/purchases': typeof AuthenticatedOwnerPurchasesRoute
  '/owner/reports': typeof AuthenticatedOwnerReportsRoute
  '/owner/reviews': typeof AuthenticatedOwnerReviewsRoute
  '/owner/rewards': typeof AuthenticatedOwnerRewardsRoute
  '/owner/riders': typeof AuthenticatedOwnerRidersRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/staff': typeof AuthenticatedOwnerStaffRoute
  '/owner/staff-accounts': typeof AuthenticatedOwnerStaffAccountsRoute
  '/owner/suppliers': typeof AuthenticatedOwnerSuppliersRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/account/review/$orderId': typeof AuthenticatedAccountReviewOrderIdRoute
  '/owner/customers/$customerId': typeof AuthenticatedOwnerCustomersCustomerIdRoute
  '/owner/orders/$orderId': typeof AuthenticatedOwnerOrdersOrderIdRoute
  '/api/public/auth/sms-hook': typeof ApiPublicAuthSmsHookRoute
  '/api/public/cleanup/run': typeof ApiPublicCleanupRunRoute
  '/api/public/notifications/dispatch': typeof ApiPublicNotificationsDispatchRoute
  '/owner/orders': typeof AuthenticatedOwnerOrdersIndexRoute
  '/api/public/communication/webhook/$provider': typeof ApiPublicCommunicationWebhookProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/offers': typeof OffersRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/menu/$productSlug': typeof MenuProductSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/menu/': typeof MenuIndexRoute
  '/_authenticated/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/_authenticated/account/challenges': typeof AuthenticatedAccountChallengesRoute
  '/_authenticated/account/favorites': typeof AuthenticatedAccountFavoritesRoute
  '/_authenticated/account/inbox': typeof AuthenticatedAccountInboxRoute
  '/_authenticated/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/account/rewards': typeof AuthenticatedAccountRewardsRoute
  '/_authenticated/account/vouchers': typeof AuthenticatedAccountVouchersRoute
  '/_authenticated/owner/account': typeof AuthenticatedOwnerAccountRoute
  '/_authenticated/owner/banners': typeof AuthenticatedOwnerBannersRoute
  '/_authenticated/owner/challenges': typeof AuthenticatedOwnerChallengesRoute
  '/_authenticated/owner/combos': typeof AuthenticatedOwnerCombosRoute
  '/_authenticated/owner/coupons': typeof AuthenticatedOwnerCouponsRoute
  '/_authenticated/owner/customers': typeof AuthenticatedOwnerCustomersRouteWithChildren
  '/_authenticated/owner/delivery': typeof AuthenticatedOwnerDeliveryRoute
  '/_authenticated/owner/finance': typeof AuthenticatedOwnerFinanceRoute
  '/_authenticated/owner/inbox': typeof AuthenticatedOwnerInboxRoute
  '/_authenticated/owner/inventory': typeof AuthenticatedOwnerInventoryRoute
  '/_authenticated/owner/menu': typeof AuthenticatedOwnerMenuRoute
  '/_authenticated/owner/my-account': typeof AuthenticatedOwnerMyAccountRoute
  '/_authenticated/owner/orders': typeof AuthenticatedOwnerOrdersRouteWithChildren
  '/_authenticated/owner/platform-sale': typeof AuthenticatedOwnerPlatformSaleRoute
  '/_authenticated/owner/platforms': typeof AuthenticatedOwnerPlatformsRoute
  '/_authenticated/owner/pos': typeof AuthenticatedOwnerPosRoute
  '/_authenticated/owner/purchases': typeof AuthenticatedOwnerPurchasesRoute
  '/_authenticated/owner/reports': typeof AuthenticatedOwnerReportsRoute
  '/_authenticated/owner/reviews': typeof AuthenticatedOwnerReviewsRoute
  '/_authenticated/owner/rewards': typeof AuthenticatedOwnerRewardsRoute
  '/_authenticated/owner/riders': typeof AuthenticatedOwnerRidersRoute
  '/_authenticated/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/_authenticated/owner/staff': typeof AuthenticatedOwnerStaffRoute
  '/_authenticated/owner/staff-accounts': typeof AuthenticatedOwnerStaffAccountsRoute
  '/_authenticated/owner/suppliers': typeof AuthenticatedOwnerSuppliersRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/account/review/$orderId': typeof AuthenticatedAccountReviewOrderIdRoute
  '/_authenticated/owner/customers/$customerId': typeof AuthenticatedOwnerCustomersCustomerIdRoute
  '/_authenticated/owner/orders/$orderId': typeof AuthenticatedOwnerOrdersOrderIdRoute
  '/api/public/auth/sms-hook': typeof ApiPublicAuthSmsHookRoute
  '/api/public/cleanup/run': typeof ApiPublicCleanupRunRoute
  '/api/public/notifications/dispatch': typeof ApiPublicNotificationsDispatchRoute
  '/_authenticated/owner/orders/': typeof AuthenticatedOwnerOrdersIndexRoute
  '/api/public/communication/webhook/$provider': typeof ApiPublicCommunicationWebhookProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/combos'
    | '/contact'
    | '/forgot-password'
    | '/offers'
    | '/kitchen'
    | '/owner'
    | '/menu/$productSlug'
    | '/order/$orderId'
    | '/track/$orderId'
    | '/menu/'
    | '/account/addresses'
    | '/account/challenges'
    | '/account/favorites'
    | '/account/inbox'
    | '/account/notifications'
    | '/account/orders'
    | '/account/rewards'
    | '/account/vouchers'
    | '/owner/account'
    | '/owner/banners'
    | '/owner/challenges'
    | '/owner/combos'
    | '/owner/coupons'
    | '/owner/customers'
    | '/owner/delivery'
    | '/owner/finance'
    | '/owner/inbox'
    | '/owner/inventory'
    | '/owner/menu'
    | '/owner/my-account'
    | '/owner/orders'
    | '/owner/platform-sale'
    | '/owner/platforms'
    | '/owner/pos'
    | '/owner/purchases'
    | '/owner/reports'
    | '/owner/reviews'
    | '/owner/rewards'
    | '/owner/riders'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/staff-accounts'
    | '/owner/suppliers'
    | '/account/'
    | '/owner/'
    | '/account/review/$orderId'
    | '/owner/customers/$customerId'
    | '/owner/orders/$orderId'
    | '/api/public/auth/sms-hook'
    | '/api/public/cleanup/run'
    | '/api/public/notifications/dispatch'
    | '/owner/orders/'
    | '/api/public/communication/webhook/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/combos'
    | '/contact'
    | '/forgot-password'
    | '/offers'
    | '/kitchen'
    | '/menu/$productSlug'
    | '/order/$orderId'
    | '/track/$orderId'
    | '/menu'
    | '/account/addresses'
    | '/account/challenges'
    | '/account/favorites'
    | '/account/inbox'
    | '/account/notifications'
    | '/account/orders'
    | '/account/rewards'
    | '/account/vouchers'
    | '/owner/account'
    | '/owner/banners'
    | '/owner/challenges'
    | '/owner/combos'
    | '/owner/coupons'
    | '/owner/customers'
    | '/owner/delivery'
    | '/owner/finance'
    | '/owner/inbox'
    | '/owner/inventory'
    | '/owner/menu'
    | '/owner/my-account'
    | '/owner/platform-sale'
    | '/owner/platforms'
    | '/owner/pos'
    | '/owner/purchases'
    | '/owner/reports'
    | '/owner/reviews'
    | '/owner/rewards'
    | '/owner/riders'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/staff-accounts'
    | '/owner/suppliers'
    | '/account'
    | '/owner'
    | '/account/review/$orderId'
    | '/owner/customers/$customerId'
    | '/owner/orders/$orderId'
    | '/api/public/auth/sms-hook'
    | '/api/public/cleanup/run'
    | '/api/public/notifications/dispatch'
    | '/owner/orders'
    | '/api/public/communication/webhook/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/combos'
    | '/contact'
    | '/forgot-password'
    | '/offers'
    | '/_authenticated/kitchen'
    | '/_authenticated/owner'
    | '/menu/$productSlug'
    | '/order/$orderId'
    | '/track/$orderId'
    | '/menu/'
    | '/_authenticated/account/addresses'
    | '/_authenticated/account/challenges'
    | '/_authenticated/account/favorites'
    | '/_authenticated/account/inbox'
    | '/_authenticated/account/notifications'
    | '/_authenticated/account/orders'
    | '/_authenticated/account/rewards'
    | '/_authenticated/account/vouchers'
    | '/_authenticated/owner/account'
    | '/_authenticated/owner/banners'
    | '/_authenticated/owner/challenges'
    | '/_authenticated/owner/combos'
    | '/_authenticated/owner/coupons'
    | '/_authenticated/owner/customers'
    | '/_authenticated/owner/delivery'
    | '/_authenticated/owner/finance'
    | '/_authenticated/owner/inbox'
    | '/_authenticated/owner/inventory'
    | '/_authenticated/owner/menu'
    | '/_authenticated/owner/my-account'
    | '/_authenticated/owner/orders'
    | '/_authenticated/owner/platform-sale'
    | '/_authenticated/owner/platforms'
    | '/_authenticated/owner/pos'
    | '/_authenticated/owner/purchases'
    | '/_authenticated/owner/reports'
    | '/_authenticated/owner/reviews'
    | '/_authenticated/owner/rewards'
    | '/_authenticated/owner/riders'
    | '/_authenticated/owner/settings'
    | '/_authenticated/owner/staff'
    | '/_authenticated/owner/staff-accounts'
    | '/_authenticated/owner/suppliers'
    | '/_authenticated/account/'
    | '/_authenticated/owner/'
    | '/_authenticated/account/review/$orderId'
    | '/_authenticated/owner/customers/$customerId'
    | '/_authenticated/owner/orders/$orderId'
    | '/api/public/auth/sms-hook'
    | '/api/public/cleanup/run'
    | '/api/public/notifications/dispatch'
    | '/_authenticated/owner/orders/'
    | '/api/public/communication/webhook/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CombosRoute: typeof CombosRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OffersRoute: typeof OffersRoute
  MenuProductSlugRoute: typeof MenuProductSlugRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  TrackOrderIdRoute: typeof TrackOrderIdRoute
  MenuIndexRoute: typeof MenuIndexRoute
  ApiPublicAuthSmsHookRoute: typeof ApiPublicAuthSmsHookRoute
  ApiPublicCleanupRunRoute: typeof ApiPublicCleanupRunRoute
  ApiPublicNotificationsDispatchRoute: typeof ApiPublicNotificationsDispatchRoute
  ApiPublicCommunicationWebhookProviderRoute: typeof ApiPublicCommunicationWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$productSlug': {
      id: '/menu/$productSlug'
      path: '/menu/$productSlug'
      fullPath: '/menu/$productSlug'
      preLoaderRoute: typeof MenuProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/addresses': {
      id: '/_authenticated/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AuthenticatedAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/challenges': {
      id: '/_authenticated/account/challenges'
      path: '/account/challenges'
      fullPath: '/account/challenges'
      preLoaderRoute: typeof AuthenticatedAccountChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/favorites': {
      id: '/_authenticated/account/favorites'
      path: '/account/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AuthenticatedAccountFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/inbox': {
      id: '/_authenticated/account/inbox'
      path: '/account/inbox'
      fullPath: '/account/inbox'
      preLoaderRoute: typeof AuthenticatedAccountInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/notifications': {
      id: '/_authenticated/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/rewards': {
      id: '/_authenticated/account/rewards'
      path: '/account/rewards'
      fullPath: '/account/rewards'
      preLoaderRoute: typeof AuthenticatedAccountRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/vouchers': {
      id: '/_authenticated/account/vouchers'
      path: '/account/vouchers'
      fullPath: '/account/vouchers'
      preLoaderRoute: typeof AuthenticatedAccountVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/account': {
      id: '/_authenticated/owner/account'
      path: '/account'
      fullPath: '/owner/account'
      preLoaderRoute: typeof AuthenticatedOwnerAccountRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/banners': {
      id: '/_authenticated/owner/banners'
      path: '/banners'
      fullPath: '/owner/banners'
      preLoaderRoute: typeof AuthenticatedOwnerBannersRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/challenges': {
      id: '/_authenticated/owner/challenges'
      path: '/challenges'
      fullPath: '/owner/challenges'
      preLoaderRoute: typeof AuthenticatedOwnerChallengesRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/combos': {
      id: '/_authenticated/owner/combos'
      path: '/combos'
      fullPath: '/owner/combos'
      preLoaderRoute: typeof AuthenticatedOwnerCombosRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/coupons': {
      id: '/_authenticated/owner/coupons'
      path: '/coupons'
      fullPath: '/owner/coupons'
      preLoaderRoute: typeof AuthenticatedOwnerCouponsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/customers': {
      id: '/_authenticated/owner/customers'
      path: '/customers'
      fullPath: '/owner/customers'
      preLoaderRoute: typeof AuthenticatedOwnerCustomersRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/delivery': {
      id: '/_authenticated/owner/delivery'
      path: '/delivery'
      fullPath: '/owner/delivery'
      preLoaderRoute: typeof AuthenticatedOwnerDeliveryRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/finance': {
      id: '/_authenticated/owner/finance'
      path: '/finance'
      fullPath: '/owner/finance'
      preLoaderRoute: typeof AuthenticatedOwnerFinanceRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/inbox': {
      id: '/_authenticated/owner/inbox'
      path: '/inbox'
      fullPath: '/owner/inbox'
      preLoaderRoute: typeof AuthenticatedOwnerInboxRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/inventory': {
      id: '/_authenticated/owner/inventory'
      path: '/inventory'
      fullPath: '/owner/inventory'
      preLoaderRoute: typeof AuthenticatedOwnerInventoryRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/menu': {
      id: '/_authenticated/owner/menu'
      path: '/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof AuthenticatedOwnerMenuRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/my-account': {
      id: '/_authenticated/owner/my-account'
      path: '/my-account'
      fullPath: '/owner/my-account'
      preLoaderRoute: typeof AuthenticatedOwnerMyAccountRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/orders': {
      id: '/_authenticated/owner/orders'
      path: '/orders'
      fullPath: '/owner/orders'
      preLoaderRoute: typeof AuthenticatedOwnerOrdersRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/platform-sale': {
      id: '/_authenticated/owner/platform-sale'
      path: '/platform-sale'
      fullPath: '/owner/platform-sale'
      preLoaderRoute: typeof AuthenticatedOwnerPlatformSaleRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/platforms': {
      id: '/_authenticated/owner/platforms'
      path: '/platforms'
      fullPath: '/owner/platforms'
      preLoaderRoute: typeof AuthenticatedOwnerPlatformsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/pos': {
      id: '/_authenticated/owner/pos'
      path: '/pos'
      fullPath: '/owner/pos'
      preLoaderRoute: typeof AuthenticatedOwnerPosRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/purchases': {
      id: '/_authenticated/owner/purchases'
      path: '/purchases'
      fullPath: '/owner/purchases'
      preLoaderRoute: typeof AuthenticatedOwnerPurchasesRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/reports': {
      id: '/_authenticated/owner/reports'
      path: '/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof AuthenticatedOwnerReportsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/reviews': {
      id: '/_authenticated/owner/reviews'
      path: '/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof AuthenticatedOwnerReviewsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/rewards': {
      id: '/_authenticated/owner/rewards'
      path: '/rewards'
      fullPath: '/owner/rewards'
      preLoaderRoute: typeof AuthenticatedOwnerRewardsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/riders': {
      id: '/_authenticated/owner/riders'
      path: '/riders'
      fullPath: '/owner/riders'
      preLoaderRoute: typeof AuthenticatedOwnerRidersRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/settings': {
      id: '/_authenticated/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof AuthenticatedOwnerSettingsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/staff': {
      id: '/_authenticated/owner/staff'
      path: '/staff'
      fullPath: '/owner/staff'
      preLoaderRoute: typeof AuthenticatedOwnerStaffRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/staff-accounts': {
      id: '/_authenticated/owner/staff-accounts'
      path: '/staff-accounts'
      fullPath: '/owner/staff-accounts'
      preLoaderRoute: typeof AuthenticatedOwnerStaffAccountsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/suppliers': {
      id: '/_authenticated/owner/suppliers'
      path: '/suppliers'
      fullPath: '/owner/suppliers'
      preLoaderRoute: typeof AuthenticatedOwnerSuppliersRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/account/review/$orderId': {
      id: '/_authenticated/account/review/$orderId'
      path: '/account/review/$orderId'
      fullPath: '/account/review/$orderId'
      preLoaderRoute: typeof AuthenticatedAccountReviewOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/customers/$customerId': {
      id: '/_authenticated/owner/customers/$customerId'
      path: '/$customerId'
      fullPath: '/owner/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedOwnerCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedOwnerCustomersRoute
    }
    '/_authenticated/owner/orders/': {
      id: '/_authenticated/owner/orders/'
      path: '/'
      fullPath: '/owner/orders/'
      preLoaderRoute: typeof AuthenticatedOwnerOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerOrdersRoute
    }
    '/_authenticated/owner/orders/$orderId': {
      id: '/_authenticated/owner/orders/$orderId'
      path: '/$orderId'
      fullPath: '/owner/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOwnerOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOwnerOrdersRoute
    }
    '/api/public/auth/sms-hook': {
      id: '/api/public/auth/sms-hook'
      path: '/api/public/auth/sms-hook'
      fullPath: '/api/public/auth/sms-hook'
      preLoaderRoute: typeof ApiPublicAuthSmsHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cleanup/run': {
      id: '/api/public/cleanup/run'
      path: '/api/public/cleanup/run'
      fullPath: '/api/public/cleanup/run'
      preLoaderRoute: typeof ApiPublicCleanupRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications/dispatch': {
      id: '/api/public/notifications/dispatch'
      path: '/api/public/notifications/dispatch'
      fullPath: '/api/public/notifications/dispatch'
      preLoaderRoute: typeof ApiPublicNotificationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/communication/webhook/$provider': {
      id: '/api/public/communication/webhook/$provider'
      path: '/api/public/communication/webhook/$provider'
      fullPath: '/api/public/communication/webhook/$provider'
      preLoaderRoute: typeof ApiPublicCommunicationWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOwnerCustomersRouteChildren {
  AuthenticatedOwnerCustomersCustomerIdRoute: typeof AuthenticatedOwnerCustomersCustomerIdRoute
}

const AuthenticatedOwnerCustomersRouteChildren: AuthenticatedOwnerCustomersRouteChildren =
  {
    AuthenticatedOwnerCustomersCustomerIdRoute:
      AuthenticatedOwnerCustomersCustomerIdRoute,
  }

const AuthenticatedOwnerCustomersRouteWithChildren =
  AuthenticatedOwnerCustomersRoute._addFileChildren(
    AuthenticatedOwnerCustomersRouteChildren,
  )

interface AuthenticatedOwnerOrdersRouteChildren {
  AuthenticatedOwnerOrdersOrderIdRoute: typeof AuthenticatedOwnerOrdersOrderIdRoute
  AuthenticatedOwnerOrdersIndexRoute: typeof AuthenticatedOwnerOrdersIndexRoute
}

const AuthenticatedOwnerOrdersRouteChildren: AuthenticatedOwnerOrdersRouteChildren =
  {
    AuthenticatedOwnerOrdersOrderIdRoute: AuthenticatedOwnerOrdersOrderIdRoute,
    AuthenticatedOwnerOrdersIndexRoute: AuthenticatedOwnerOrdersIndexRoute,
  }

const AuthenticatedOwnerOrdersRouteWithChildren =
  AuthenticatedOwnerOrdersRoute._addFileChildren(
    AuthenticatedOwnerOrdersRouteChildren,
  )

interface AuthenticatedOwnerRouteChildren {
  AuthenticatedOwnerAccountRoute: typeof AuthenticatedOwnerAccountRoute
  AuthenticatedOwnerBannersRoute: typeof AuthenticatedOwnerBannersRoute
  AuthenticatedOwnerChallengesRoute: typeof AuthenticatedOwnerChallengesRoute
  AuthenticatedOwnerCombosRoute: typeof AuthenticatedOwnerCombosRoute
  AuthenticatedOwnerCouponsRoute: typeof AuthenticatedOwnerCouponsRoute
  AuthenticatedOwnerCustomersRoute: typeof AuthenticatedOwnerCustomersRouteWithChildren
  AuthenticatedOwnerDeliveryRoute: typeof AuthenticatedOwnerDeliveryRoute
  AuthenticatedOwnerFinanceRoute: typeof AuthenticatedOwnerFinanceRoute
  AuthenticatedOwnerInboxRoute: typeof AuthenticatedOwnerInboxRoute
  AuthenticatedOwnerInventoryRoute: typeof AuthenticatedOwnerInventoryRoute
  AuthenticatedOwnerMenuRoute: typeof AuthenticatedOwnerMenuRoute
  AuthenticatedOwnerMyAccountRoute: typeof AuthenticatedOwnerMyAccountRoute
  AuthenticatedOwnerOrdersRoute: typeof AuthenticatedOwnerOrdersRouteWithChildren
  AuthenticatedOwnerPlatformSaleRoute: typeof AuthenticatedOwnerPlatformSaleRoute
  AuthenticatedOwnerPlatformsRoute: typeof AuthenticatedOwnerPlatformsRoute
  AuthenticatedOwnerPosRoute: typeof AuthenticatedOwnerPosRoute
  AuthenticatedOwnerPurchasesRoute: typeof AuthenticatedOwnerPurchasesRoute
  AuthenticatedOwnerReportsRoute: typeof AuthenticatedOwnerReportsRoute
  AuthenticatedOwnerReviewsRoute: typeof AuthenticatedOwnerReviewsRoute
  AuthenticatedOwnerRewardsRoute: typeof AuthenticatedOwnerRewardsRoute
  AuthenticatedOwnerRidersRoute: typeof AuthenticatedOwnerRidersRoute
  AuthenticatedOwnerSettingsRoute: typeof AuthenticatedOwnerSettingsRoute
  AuthenticatedOwnerStaffRoute: typeof AuthenticatedOwnerStaffRoute
  AuthenticatedOwnerStaffAccountsRoute: typeof AuthenticatedOwnerStaffAccountsRoute
  AuthenticatedOwnerSuppliersRoute: typeof AuthenticatedOwnerSuppliersRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
}

const AuthenticatedOwnerRouteChildren: AuthenticatedOwnerRouteChildren = {
  AuthenticatedOwnerAccountRoute: AuthenticatedOwnerAccountRoute,
  AuthenticatedOwnerBannersRoute: AuthenticatedOwnerBannersRoute,
  AuthenticatedOwnerChallengesRoute: AuthenticatedOwnerChallengesRoute,
  AuthenticatedOwnerCombosRoute: AuthenticatedOwnerCombosRoute,
  AuthenticatedOwnerCouponsRoute: AuthenticatedOwnerCouponsRoute,
  AuthenticatedOwnerCustomersRoute:
    AuthenticatedOwnerCustomersRouteWithChildren,
  AuthenticatedOwnerDeliveryRoute: AuthenticatedOwnerDeliveryRoute,
  AuthenticatedOwnerFinanceRoute: AuthenticatedOwnerFinanceRoute,
  AuthenticatedOwnerInboxRoute: AuthenticatedOwnerInboxRoute,
  AuthenticatedOwnerInventoryRoute: AuthenticatedOwnerInventoryRoute,
  AuthenticatedOwnerMenuRoute: AuthenticatedOwnerMenuRoute,
  AuthenticatedOwnerMyAccountRoute: AuthenticatedOwnerMyAccountRoute,
  AuthenticatedOwnerOrdersRoute: AuthenticatedOwnerOrdersRouteWithChildren,
  AuthenticatedOwnerPlatformSaleRoute: AuthenticatedOwnerPlatformSaleRoute,
  AuthenticatedOwnerPlatformsRoute: AuthenticatedOwnerPlatformsRoute,
  AuthenticatedOwnerPosRoute: AuthenticatedOwnerPosRoute,
  AuthenticatedOwnerPurchasesRoute: AuthenticatedOwnerPurchasesRoute,
  AuthenticatedOwnerReportsRoute: AuthenticatedOwnerReportsRoute,
  AuthenticatedOwnerReviewsRoute: AuthenticatedOwnerReviewsRoute,
  AuthenticatedOwnerRewardsRoute: AuthenticatedOwnerRewardsRoute,
  AuthenticatedOwnerRidersRoute: AuthenticatedOwnerRidersRoute,
  AuthenticatedOwnerSettingsRoute: AuthenticatedOwnerSettingsRoute,
  AuthenticatedOwnerStaffRoute: AuthenticatedOwnerStaffRoute,
  AuthenticatedOwnerStaffAccountsRoute: AuthenticatedOwnerStaffAccountsRoute,
  AuthenticatedOwnerSuppliersRoute: AuthenticatedOwnerSuppliersRoute,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
}

const AuthenticatedOwnerRouteWithChildren =
  AuthenticatedOwnerRoute._addFileChildren(AuthenticatedOwnerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRouteWithChildren
  AuthenticatedAccountAddressesRoute: typeof AuthenticatedAccountAddressesRoute
  AuthenticatedAccountChallengesRoute: typeof AuthenticatedAccountChallengesRoute
  AuthenticatedAccountFavoritesRoute: typeof AuthenticatedAccountFavoritesRoute
  AuthenticatedAccountInboxRoute: typeof AuthenticatedAccountInboxRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountRewardsRoute: typeof AuthenticatedAccountRewardsRoute
  AuthenticatedAccountVouchersRoute: typeof AuthenticatedAccountVouchersRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAccountReviewOrderIdRoute: typeof AuthenticatedAccountReviewOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRouteWithChildren,
  AuthenticatedAccountAddressesRoute: AuthenticatedAccountAddressesRoute,
  AuthenticatedAccountChallengesRoute: AuthenticatedAccountChallengesRoute,
  AuthenticatedAccountFavoritesRoute: AuthenticatedAccountFavoritesRoute,
  AuthenticatedAccountInboxRoute: AuthenticatedAccountInboxRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
  AuthenticatedAccountRewardsRoute: AuthenticatedAccountRewardsRoute,
  AuthenticatedAccountVouchersRoute: AuthenticatedAccountVouchersRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAccountReviewOrderIdRoute:
    AuthenticatedAccountReviewOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CombosRoute: CombosRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OffersRoute: OffersRoute,
  MenuProductSlugRoute: MenuProductSlugRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  TrackOrderIdRoute: TrackOrderIdRoute,
  MenuIndexRoute: MenuIndexRoute,
  ApiPublicAuthSmsHookRoute: ApiPublicAuthSmsHookRoute,
  ApiPublicCleanupRunRoute: ApiPublicCleanupRunRoute,
  ApiPublicNotificationsDispatchRoute: ApiPublicNotificationsDispatchRoute,
  ApiPublicCommunicationWebhookProviderRoute:
    ApiPublicCommunicationWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
