// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

function expectedIssuer(): string | undefined {
  const url = import.meta.env['VITE_SUPABASE_URL'] as string | undefined
  return url ? `${url.replace(/\/+$/, '')}/auth/v1` : undefined
}

// A session saved by a different Supabase project (e.g. after switching backends)
// can never be validated by the current one, so drop it instead of sending it.
function isForeignToken(token: string): boolean {
  const issuer = expectedIssuer()
  if (!issuer) return false
  try {
    const parts = token.split('.')
    if (parts.length !== 3) return true
    const payload = JSON.parse(
      atob(parts[1]!.replace(/-/g, '+').replace(/_/g, '/')),
    ) as { iss?: string }
    return typeof payload.iss === 'string' && payload.iss !== issuer
  } catch {
    return true
  }
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token

    if (token && isForeignToken(token)) {
      await supabase.auth.signOut({ scope: 'local' }).catch(() => {})
      return next({ headers: {} })
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
